export const HOME = '/'
export const Product_List = '/product_list'
export const Single_Product = '/single/:paramId'
export const Single_Product_ID = '/single/'
export const Admin_Panel = '/admin/'
export const Add_Product = '/admin/add_Product/'
export const Add_User = '/admin/add_User/'
export const Add_Categorie = '/admin/add_Categorie/'